version: '2'

services:

  db0:
    container_name: redis0
    hostname: redis0
    image: redis
    networks:
    - backend

  db1:
    image: mongo

  web0:
    build: ./web0
    ports:
     - "5000:5000"
    volumes:
     - ./web0:/app
    depends_on:
    - "db0"
    networks:
     - backend

  web1:
    build: ./web1
    ports:
     - "8070:8069"
    volumes:
     - ./web1:/app
    depends_on:
    - "db0"
    networks:
     - backend

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis0:6379
    - "db0"
    networks:
    - backend
    ports:
    - "8081:8081"

  mongo-express:
      image: mongo-express
      environment:
          - ME_CONFIG_MONGODB_SERVER=172.19.0.2
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
          - VCAP_APP_PORT=8082
      depends_on:
          - "db1"
      ports:
        - "8082:8082"

networks:
    backend:
      driver: bridge
